### ISSUE TITLE
Easier authentication

### ISSUE THREAD

**Issue by Stubatiger** [kodless/leek#11]
Hello, first and foremost i really love leek.
Its such a huge step from flower or other celery monitoring tools, its incredible. Great work.

My pain currently is that as i have understood it, that authentication cannot be disabled and can only be done with Firebase.

I can probably understand the reasoning behind that, but for me the setup process for the authentication is really cumbersome and for starters who just want to try leek, i can imagine they get scared by it and in the end miss out on the awesomeness of leek.

Can there be anything done like turning off authentication completely or just using simple BasicAuth or some static Usernames/Passwords?

**Comment by kodless** [comment]
Thanks for your feedback 👍 

Sure, will work on supporting no-auth and basic auth.

**Comment by kodless** [comment]
no-auth support is merged to master and it will be delivered in version 0.4.0 after updating docs, testing and preparing docker-compose-no-auth.yml demo file under demo folder.

**Comment by kodless** [comment]
no-auth support is delivered in version 0.4.0, hopefully we can also support basic-auth in the future!
