### ISSUE TITLE
Auto-refresh pages so it gives real-time monitoring

### ISSUE THREAD

**Issue by ezhlobo** [kodless/leek#3]
**Is your feature request related to a problem? Please describe.**
It's not a real problem but makes our usage experience not so convenient. When I look at tasks I see how time is ticking near each task, but new tasks are not appearing — which makes me nervous and forces to constantly click refresh button :).

**Describe the solution you'd like**
It would be nice to re-fresh the data on each page periodically. Let's say every 1-2 seconds we refresh data.

**Describe alternatives you've considered**
Currently we force people to press refresh button, but we could do that for them. Another alternative would be to organize a way when API pushes changes to web (websockets, or long polling). But I think just doing same request periodically is the easiest.

**Additional context**
_empty_

**Comment by kodless** [comment]
@ezhlobo thanks for your feedback!

This is ready in version [0.6.8](https://github.com/kodless/leek/releases/tag/0.6.8)
