### ISSUE TITLE
Workers are not filtered by environment

### ISSUE THREAD

**Issue by ezhlobo** [kodless/leek#4]
**Describe the bug**
When there are different environments we output data on each page according to that environment. But on Workers page we output all workers regardless of the environment. 

**To Reproduce**
1. Setup workers for multiple environments and subscribe to them
2. Select one environment
3. Go to Workers page

**Expected behavior**
See workers associated with selected environment.

**Screenshots**
_empty_

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser firefox
 - Version 88

**Smartphone (please complete the following information):**
_empty_

**Additional context**
_empty_

**Comment by kodless** [comment]
Fix will be introduced in version 0.3.8

**Comment by kodless** [comment]
Fix introduced in version 0.3.8
