### ISSUE TITLE
Make sure we can select multiple states when filter tasks

### ISSUE THREAD

**Issue by ezhlobo** [kodless/leek#5]
**Is your feature request related to a problem? Please describe.**
Currently I have several tasks that are in Recovered/Failed states and I can't get them all to easily analyze what happned there. This problem could be solved by making Issue reference rlated tasks, but it's not available too. Another case is to get Queued/Received tasks to analyzy what's up with them.

**Describe the solution you'd like**
If we made filtering by multiple states, then that would solve the issue and it would let me get necessary bunch of tasks.

**Describe alternatives you've considered**
I have to firstly search by one state and then by another instead of getting everything on one list.

**Additional context**
_empty_

**Comment by ezhlobo** [comment]
It might be applicable to other items. For example combining queues, names, workers is also good to have.

**Comment by kodless** [comment]
Will make sure to implement this ASAP.

Thanks for your feedback!

**Comment by kodless** [comment]
Feature will be introduced in version 0.3.8

**Comment by ezhlobo** [comment]
@kodless thank you very much, I can't wait for 0.3.9 already 😎

**Comment by kodless** [comment]
Feature introduced in version 0.3.8
