### ISSUE TITLE
Environment changing when selecting a task

### ISSUE THREAD

**Issue by stfloyd** [kodless/leek#50]
**Describe the bug**
While in another env and selecting a task - the env you are in viewing the tasks will appear to change to the agent's first subscription's `app_env`.

**To Reproduce**
1. Ensure there is an active & on agent with at least 2 subscriptions containing different `app_env`'s.
2. Change the env via the dropdown at the top right to any other env than default.
3. Go to Tasks via top menu bar.
4. Select any task, and verify the env that is now selected via that same dropdown used to change.
5. Browse around to verify that the env has indeed changed.

**Expected behavior**
If I have two subscriptions with `app_env`'s respectively:
- prod
- dev
I would expect if I changed the env via the dropdown at the top right to 'dev' to stay in 'dev' when I select to view a task's details or perform any other action.

**Comment by kodless** [comment]
The fix will be introduced in version 0.5.6
