### ISSUE TITLE
When deleting the only one application and creating a new one, the deleted application is still selected

### ISSUE THREAD

**Issue by lesha1201** [kodless/leek#6]
**Describe the bug**
When deleting the only one application and creating a new one, the deleted application is still selected instead of selecting a new one. Because the old app is selected, there are errors:

![image](https://user-images.githubusercontent.com/10157660/115834395-dafdb900-a41d-11eb-80d0-6db37db12f46.png)

**To Reproduce**
1. Create a new application. Make sure there is only one app
2. Go to applications and delete the application
3. It will prompt to create a new one. Create it
4. See error popping up because the deleted app is still selected

**Expected behavior**
The new app should be autoselected

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome v90

**Comment by kodless** [comment]
Thanks for your feedback, will make sure to fix the issue ASAP!

**Comment by kodless** [comment]
Fix released in version 0.4.8
