### ISSUE TITLE
Make options in state filter persistent even when there are 0 related tasks

### ISSUE THREAD

**Issue by ezhlobo** [kodless/leek#9]
**Is your feature request related to a problem? Please describe.**
When I have a small amount of tasks it's tricky to ctch the moment when I do have tasks in STARTED state. So I can't filter by them to monitor in real time. 

**Describe the solution you'd like**
Would be great to see all states ever met (or ever possibl) in that select.

**Describe alternatives you've considered**
Reload until I get something in Started state to filter by them. But that's nott the best experince :).

**Additional context**
_empty_

**Comment by kodless** [comment]
@ezhlobo many thanks for your continuous feedback, patch will be introduced in version 0.3.8.

**Comment by kodless** [comment]
Patch introduced in version 0.3.8
